group 'com.crazecoder.openfile'
version '1.0-SNAPSHOT'

buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.4'
    }
}

rootProject.allprojects {
    repositories {
        google()
        jcenter()
    }
}

apply plugin: 'com.android.library'

android {
    if (project.android.hasProperty('namespace')) {
        namespace 'com.crazecoder.openfile"'
    }

    compileSdk 34

    defaultConfig {
        minSdkVersion 16
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}
dependencies{
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
}